ASG/Areas/FinancialPlanner/Models/Budget.cs
using ASG.Areas.FinancialPlanner.Models;
using ASG.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ASG.Areas.FinancialPlanner.Models
{
    public class Budget
    {

        public Budget()
        {
            Users = new HashSet<ApplicationUser>();
            BudgetItems = new HashSet<BudgetItem>();
        }
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Amount { get; set; }
        public decimal BudgetRemaining { get; set; }
        public string Description { get; set; }
        public decimal? SuggestedAmount { get; set; }
        public int BudgetEndDate { get; set; }
        public DateTime BudgetEnd { get; set; }
        public DateTime BudgetStartDate { get; set; }
        public bool Expired { get; set; }



        public string UserId { get; set; }

        public int? BudgetDurationPeriodId { get; set; }
        public virtual BudgetDurationPeriod BudgetDurationPeriod { get; set; }


        public int HouseholdId { get; set; }
        public virtual Household Household { get; set; }



        public virtual ICollection<ApplicationUser> Users { get; set; }


        public virtual ICollection<BudgetItem> BudgetItems { get; set; }

        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}

ASG/Areas/FinancialPlanner/Models/BudgetHouseholdViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ASG.Areas.FinancialPlanner.Models
{
    public class BudgetHouseholdViewModel
    {
        public Budget budget { get; set; }
        public IList<Budget> budgetb { get; set; }
        public Household household { get; set; }
        public ICollection<Budget> budgets { get; set; }
        public ICollection<Household> Households { get; set; }
    }
}

ASG/Areas/FinancialPlanner/Controllers/BudgetsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ASG.Areas.FinancialPlanner.Models;
using Microsoft.AspNet.Identity;
using ASG.Models;

namespace ASG.Areas.FinancialPlanner.Controllers
{
    public class BudgetsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        public ActionResult Index()
        {
            var allUsers = db.Users.ToList();
            var userId = User.Identity.GetUserId();
            var user = db.Users.Find(userId);
            var household = db.Users.FirstOrDefault(u => u.Id == userId).Household;
            var accounts = db.Accounts.FirstOrDefault(h => h.AccountHolderUserId == userId);
            List<Budget> MemberBudgets = new List<Budget>();
            if (!household.Budgets.Any())
            {
                var NoBudgets = "Oops, looks like you don't have any budgets yet.  Please go to your household and set up your budget(s)";
                TempData["budgetmessage"] = NoBudgets;
                ViewBag.BudgetAlert = "Oops, you haven't established any Budgets yet.  Click here to set up your budget to utilize the planner.";
                return RedirectToAction("Index", "Home");
            }

            foreach (var budget in
                household.Budgets)
            {
                MemberBudgets.Add(budget);
            }
            return View(MemberBudgets);
        }

        public ActionResult BudgetPartial()
        {
            var userId = User.Identity.GetUserId();
            var user = db.Users.Find(userId);
            if (userId != null)
            {
                var householdId = db.Users.FirstOrDefault(u => u.Id == userId).HouseholdId;
                if (householdId != null)
                {
                    Household household = db.Households.Find((object)householdId);
                    return PartialView("~/Areas/FinancialPlanner/Views/Budgets/_BudgetPartial.cshtml", household);
                }
                else return PartialView("~/Areas/FinancialPlanner/Views/Budgets/_BudgetPartial.cshtml");
            }
            else return PartialView("~/Areas/FinancialPlanner/Views/Budgets/_BudgetPartial.cshtml");
        }


        public ActionResult BudgetHousehold(int? id)
        {
            BudgetHouseholdViewModel MemberBudget = new BudgetHouseholdViewModel();
            var userId = User.Identity.GetUserId();
            var user = db.Users.Find(userId);
            if (userId != null)
            {
                var usersbudgets = db.Users.FirstOrDefault(u => u.Id == userId).Budgets;
                ViewBag.UserBudgets = usersbudgets;
            }

            if (userId == null)
            {
                var NotLoggedIn = "You must be logged in to view your household details.";
                TempData["message"] = NotLoggedIn;
                return RedirectToAction("Index", "Home");
            }

            else if (id == null)
            {
                var NoHousehold = "You have not set up a household yet.  Please create a household.";
                TempData["NoHouseholdmessage"] = NoHousehold;
                return RedirectToAction("Index", "Home");
            }

            MemberBudget.household = db.Households.Find(id);
            if (MemberBudget.household != null)
            {
                var users = db.Users.Where(u => u.HouseholdId == MemberBudget.household.Id).ToList();
                MemberBudget.household.Users = users;
            }

            else
            {
                var NotPartofHousehold = "You must be part of a household to view it's details.  If you have been invited to join a household, please join first by clicking 'Join Household', or create a new household.";
                TempData["message"] = NotPartofHousehold;
                return RedirectToAction("Index", "Home");
            }

            var household = db.Users.FirstOrDefault(u => u.Id == userId).Household;
            var accounts = db.Accounts.FirstOrDefault(h => h.AccountHolderUserId == userId);
            MemberBudget.budgets = db.Budgets.Where(b => b.HouseholdId == household.Id).ToList();
            MemberBudget.household = household;
            List<ApplicationUser> BudgetUsers = new List<ApplicationUser>();
            foreach (var member in MemberBudget.household.Users)
            {
                BudgetUsers.Add(member);
            }
            ViewBag.BudgetCreator = BudgetUsers;
            return View(MemberBudget);
        }
        
        // GET: Budgets
        public ActionResult BudgeterIndex()
        {
            var allUsers = db.Users.ToList();
            var userId = User.Identity.GetUserId();
            var user = db.Users.Find(userId);
            var household = db.Users.FirstOrDefault(u => u.Id == userId).Household;
            var accounts = db.Accounts.FirstOrDefault(h => h.AccountHolderUserId == userId);
            List<ApplicationUser> HouseholdMembers = new List<ApplicationUser>();
            List<Budget> MemberBudgets = new List<Budget>();
            if (!household.Budgets.Any())
            {
                var NoBudgets = "Oops, looks like you don't have any budgets yet.  Please set up a budget before proceeding.";
                TempData["budgetmessage"] = NoBudgets;
                ViewBag.BudgetAlert = "Oops, you haven't established any Budgets yet.  Click here to set up your budget to utilize the planner.";
            }

            if (!household.Accounts.Any())
            {
                var NoAccounts = "Oops, looks like you don't have any accounts yet.  Please set up a bank account before proceeding";
                TempData["accountmessage"] = NoAccounts;
                ViewBag.AccountAlert = "Oops, you haven't established any Accounts yet.  Click here to set up your accounts to utilize the planner.";
            }

            if (household.Budgets.Any() && household.Accounts.Any())
            {
                foreach (var member in db.Users.AsNoTracking())
                {
                    if (member.HouseholdId == user.HouseholdId)
                    {
                        HouseholdMembers.Add(member);
                    }
                }

                foreach (var budget in household.Budgets)
                {
                    MemberBudgets.Add(budget);
                }
                return View(MemberBudgets);
            }
            else
            {
                return RedirectToAction("Details", "Households", new { id = household.Id });
            }
        }
        
        //GET
        public PartialViewResult BudgetsCreateModal()
        {
            ViewBag.BudgetDurationPeriodId = new SelectList(db.BudgetDurationPeriods, "Id", "Description");
            ViewBag.ItemizeMessage = "Would you like to itemize this budget? By itemizing you can create categories to budget, like food, entertainment, etc.  If you wish to simply keep the budget as a total monthly budget without itemizing, press complete";
            return PartialView();
        }
        //POST

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult BudgetsCreate([Bind(Include = "Id,Name,Amount,Description,BudgetDurationPeriodId, Household")] Budget budget)
        {
            if (ModelState.IsValid)
            {

                var userId = User.Identity.GetUserId();
                var user = db.Users.Find(userId);
                var household = user.Household;
                var days = db.BudgetDurationPeriods.FirstOrDefault(b => b.Id == budget.BudgetDurationPeriodId).NumberOfDays;

                if (user.HouseholdId == null)
                {
                    household = new Household();
                    household.CreatedDate = DateTime.Now;
                    household.UserId = userId;
                    db.Households.Add(household);
                    db.SaveChanges();
                    user.HouseholdId = household.Id;

                    budget.Household = db.Households.Find(household.Id);          
                    var UsersFinancialAccounts = db.Users.Find(userId).Accounts;
                    foreach (var account in UsersFinancialAccounts)
                    {
                        account.HouseholdId = household.Id;
                    }
                    db.SaveChanges();               
                }
               
                
                budget.BudgetStartDate = DateTime.Now;
                double numberofdays = Convert.ToDouble(days);
                budget.BudgetEnd = budget.BudgetStartDate.AddDays(numberofdays);
                budget.HouseholdId = household.Id;
                budget.UserId = userId;
                budget.BudgetRemaining = budget.Amount;
                budget.BudgetEndDate = 0;
                
                List<decimal> expenses = new List<decimal>();
                foreach (var transaction in db.Transactions)
                {
                    if (transaction.CreatedDate > budget.BudgetEnd && transaction.SubmitterUserId == userId)
                    {
                        expenses.Add(transaction.Amount);
                    }
                }
                var expensetotal = expenses.Sum();
                db.Budgets.Add(budget);
                db.SaveChanges();
                ViewBag.expenses = expenses;
                return Json(new { success = true });                
            }

            var modelErrors = new List<string>();
            foreach (var modelState in ModelState.Values)
            {
                foreach (var modelError in modelState.Errors)
                {
                    modelErrors.Add(modelError.ErrorMessage);
                }
            }

            ViewBag.BudgetDurationPeriodId = new SelectList(db.BudgetDurationPeriods, "Id", "Description");

ASG/Areas/FinancialPlanner/Views/Budgets/BudgetsCreateModal.cshtml
@model ASG.Areas.FinancialPlanner.Models.Budget
@using Microsoft.AspNet.Identity


@{ var userid = User.Identity.GetUserId();

}


@{
    ViewBag.Title = "BudgetsCreateModal";
}
<div class="modal-content" id="CreateABudget">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"><img src="~/Areas/FinancialPlanner/FP_Images/fp.png" /></h4>
    </div>
    <div class="modal-body fpModal" style="padding-bottom:35px">
        <form id="CreateBudgets">
            @Html.AntiForgeryToken()
            <div class="form-horizontal">
                Enter a Budget Name
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>
                How much do you want to spend?
                <div class="form-group">
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
                    </div>
                </div>
                What is this budget for?
                <div class="form-group">
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>
                Duration
                <div class="form-group">
                    <div class="col-md-10">
                        @Html.DropDownList("BudgetDurationPeriodId", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.BudgetDurationPeriodId, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-10" style="margin-top:15px">
                        <span id="budgetCreationErrors" style="color:lime">
                        </span><br />
                        <input type="button" value="Create Budget" class="btn btn-default" style="float:left;" id="BudgetCreator" onclick="createABudget()" />
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

ASG/Areas/FinancialPlanner/Views/Budgets/BudgetsItemizeModal.cshtml
@model ASG.Areas.FinancialPlanner.Models.Transaction
@using Microsoft.AspNet.Identity


@{ var userid = User.Identity.GetUserId();

}


@{
    ViewBag.Title = "BudgetsItemizeModal";
}

<div id="myModal2" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Modal Header</h4>
            </div>
            <div class="modal-body" style="height:460px">
                <div class="container">
                    <div class="row">
                        <p>@ViewBag.ItemizeConfirm</p><br />
                    </div>
                </div>
                <div class="container">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()
                        <div class="form-horizontal">
                            <h4>Add Budget Category</h4>
                            <hr />
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group">
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.TransactionCategory.Name, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.TransactionCategory, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-10">
                                    <input type="submit" value="Add Category" class="btn btn-default" />
                                </div>
                            </div>
                        </div>
                    }
                    <div>
                        @Html.ActionLink("Back to List", "Index")
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Done</button>
            </div>
        </div>
    </div>
</div>

ASG/Areas/FinancialPlanner/Views/Budgets/Create.cshtml
@model ASG.Areas.FinancialPlanner.Models.Budget

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Budget</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SuggestedAmount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SuggestedAmount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SuggestedAmount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BudgetEndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BudgetEndDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BudgetEndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BudgetStartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BudgetStartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BudgetStartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HouseholdId, "HouseholdId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("HouseholdId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.HouseholdId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ASG/Areas/FinancialPlanner/Views/Budgets/Delete.cshtml
@model ASG.Areas.FinancialPlanner.Models.Budget
@*@{ Layout = null;}*@
@{
    ViewBag.Title = "Delete";
}


<div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"><img src="~/Areas/FinancialPlanner/FP_Images/fp.png" /></h4>
    </div>
    <div class="modal-body fpModal" style="padding-bottom:35px">
        <div class="container">
            <div class="row">
            </div>
        </div>
        Are you sure you want to delete this Budget?
        <div>
            <hr />
            <dl class="dl-flex">
                <dt>
                    Household Name
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Household.Name)
                </dd>
                <dt>
                    Budget Name
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Name)
                </dd>
                <dt>
                    Budget Amount
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Amount)
                </dd>
                <dt>
                    Budget Description
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Description)
                </dd>
                <dt>
                    Start Date
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.BudgetStartDate)
                </dd>
            </dl>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="form-actions no-color">
                    @{ var user = User.Identity;}
                    @if (user != null)
                    {
                        if (user.Name == "Administrator@Mailinator.com" || user.Name == "ProjectManager@Mailinator.com" || user.Name == "Developer@Mailinator.com" || user.Name == "GuestUser@mailinator.com")
                        {
                            <input type="submit" value="Delete" class="btn btn-default" disabled="disabled" style="float:right;" />
                        }
                        else
                        {
                            <input type="submit" value="Delete" class="btn btn-default" style="float:right" />
                        }
                    }
                </div>
                        }
            <br />
        </div>
    </div>
</div>

ASG/Areas/FinancialPlanner/Views/Budgets/Edit.cshtml
@model ASG.Areas.FinancialPlanner.Models.Budget

@{
    ViewBag.Title = "Edit";
}

<div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"><img src="~/Areas/FinancialPlanner/FP_Images/fp.png" /></h4>
    </div>
    <div class="modal-body fpModal" style="padding-bottom:35px">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="form-horizontal">
                Edit budget details
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Id)
                @Html.HiddenFor(model => model.BudgetStartDate)
                @Html.HiddenFor(model => model.HouseholdId)
                @Html.HiddenFor(model => model.BudgetEnd)
                @Html.HiddenFor(model => model.Amount)
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-default" style="float:right; width:150px" />
                    </div>
                </div>
            </div>
        }     
    </div>   
</div>

ASG/Areas/FinancialPlanner/Views/Budgets/Index.cshtml
@model IEnumerable<ASG.Areas.FinancialPlanner.Models.Budget>
@using Microsoft.AspNet.Identity
@{
    ViewBag.Title = "Index";
}
@{ var userid = User.Identity.GetUserId();

}
<h2></h2>
<br /><br />
<p>
    <h4> Budgets</h4>
</p>
<br /><br /><br />
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Amount)
        </th>      
        <th>
            @Html.DisplayNameFor(model => model.SuggestedAmount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BudgetStartDate)
        </th>
        <th>
            Budget Duration Period
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Amount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SuggestedAmount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BudgetStartDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BudgetDurationPeriod.NumberOfDays) Days
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }
</table>
<br /><br /><hr />
<div class="page-head">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2>Budget Portal</h2>
                <h4>Click image below to view your budget details</h4><br />
            </div>
        </div>
    </div>
</div>
<!-- Page Heading ends -->
<!-- Page content starts -->
<div class="content about-two">
    <div class="container">
        <div class="row">
            @foreach (var budget in Model)
            {
                <div class="col-md-3 col-sm-6  well" style="margin:0 10px 0 10px; box-shadow: 10px 10px 5px #888888;">
                    <!-- Staff #1 -->
                    <div class="staff">
                        <!-- Picture -->
                        <a href="@Url.Action("Details", "Budgets", new { id = budget.Id })">
                            <div class="pic">
                                <img src="~/img/horizontal-1714232.png" alt="" class="img-responsive" />
                            </div>
                        </a>
                        <!-- Details -->
                        <div class="details">
                            <!-- Name and designation -->
                            <div class="desig pull-left">
                                <p class="name">@budget.Name</p>
                                <em>subtitle</em>
                            </div>
                            <!-- Social media details. Replace # with profile links -->
                            <div class="asocial pull-right">
                                <a href="#"><i class="fa fa-facebook"></i></a>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                                <a href="#"><i class="fa fa-linkedin"></i></a>
                            </div>
                            <div class="clearfix"></div>
                            <!-- Description -->
                            <p class="adesc">@budget.Description </p>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
    <br /><br /><br />
    <p>
        @if (Request.IsAuthenticated)
        {
            <a href="@Url.Action("BudgetsCreateModal","Budgets", new { id = userid })" data-toggle="modal" data-target="#myModal1">Create a New Budget</a>
        }
    </p>
</div>
<br /><br /><br /><br /><hr />

ASG/Areas/FinancialPlanner/Views/Budgets/_BudgetPartial.cshtml
@model ASG.Areas.FinancialPlanner.Models.Household
@{
    ViewBag.Title = "BudgetPartial";
}
@if (Model != null)
{
    <ul class="dropdown-menu">
        @if (Request.IsAuthenticated)
        {
            <li><a href="@Url.Action("BudgetHousehold", "Budgets", new { id = Model.Id })">My Budgets</a></li>
        }
        else
        {
            <li><a onclick="openRegisterModal()">Register</a></li>
            <li><a onclick="openLoginModal()">Login</a></li>
        }
    </ul>
}

else
{
    <ul class="dropdown-menu">
        @if (Request.IsAuthenticated)
        {
            if (Model != null)
            {
                <li><a href="@Url.Action("BudgetHousehold", "Budgets", new { id = Model.Id })">My Budgets</a></li>
            }
            else
            {
                // here when you go to set up a budget, you will want to ask whether they want to set up an individual budget or a household budget
                <li><a onclick="budgetOptions()">Set Up a Budget</a></li>
            }
        }
        else
        {
            <li><a onclick="openRegisterModal()">Register</a></li>
            <li><a onclick="openLoginModal()">Login</a></li>
        }
    </ul>
}