ASG/Areas/Blog/Models/BlogPost.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ASG.Areas.Blog.Models
{
   
        public class BlogPost


        {

            public BlogPost()
            {
                Comments = new HashSet<Comment>();
                Topics = new HashSet<Topic>();
            }
            public int Id { get; set; }

            [DisplayFormat(DataFormatString = "{0:MMMM dd yyyy}")]
            public DateTimeOffset createdDate { get; set; }
            [DisplayFormat(DataFormatString = "{0:MMMM dd yyyy}")]
            public DateTimeOffset? updatedDate { get; set; }
            public string Title { get; set; }
            public string Slug { get; set; }
            [AllowHtml]
            public string Body { get; set; }
            public string MediaURL { get; set; }
            public bool Published { get; set; }


            public virtual ICollection<Comment> Comments { get; set; }
            public virtual ICollection<Topic> Topics { get; set; }
        }
    }







   

ASG/Models/BlogPost.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ASG.Models
{
    public class BlogPost


    {

        public BlogPost()
        {
            Comments = new HashSet<Comment>();
            Topics = new HashSet<Topic>();
        }
        public int Id { get; set; }

        [DisplayFormat(DataFormatString = "{0:MMMM dd yyyy}")]
        public DateTimeOffset createdDate { get; set; }
        [DisplayFormat(DataFormatString = "{0:MMMM dd yyyy}")]
        public DateTimeOffset? updatedDate { get; set; }
        public string Title { get; set; }
        public string Slug { get; set; }
        [AllowHtml]
        public string Body { get; set; }
        public string MediaURL { get; set; }
        public bool Published { get; set; }

  
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Topic>Topics { get; set; }
    }
}

ASG/Areas/Blog/Controllers/BlogPostsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ASG.Areas.Blog.Models;
using System.IO;
using PagedList;
using System.Web.Security;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using ASG.Areas.BugTracker.Models;
using Microsoft.AspNet.Identity.Owin;

namespace ASG.Areas.Blog.Controllers
{  
        //[RequireHttps]
        public class BlogPostsController : Controller
        {
            private ApplicationDbContext db = new ApplicationDbContext();
            private TopicHelper helper = new TopicHelper();      


        // GET: BlogPosts
        public ActionResult Index(int? page, string message = "")
            {
                if (message != "")
                {
                    ViewBag.Message = message;
                }


            int pageSize = 3;
                int pageNumber = (page ?? 1);
                var Published = db.Posts.Where(s => s.Published).ToList();
                return View(Published.OrderByDescending(p => p.createdDate).ToPagedList(pageNumber, pageSize));
            }

            public PartialViewResult BlogPartialUpper()
        {
            return PartialView("~/Areas/Blog/Views/BlogPosts/_UpperBlogPartialView.cshtml", db.Topics.ToList());
            }
            public PartialViewResult BlogPartialMid()
            {
                return PartialView("~/Areas/Blog/Views/BlogPosts/_MidBlogPartialView.cshtml", db.Posts.Where(s => s.Published).OrderByDescending(p => p.Comments.Count).Take(3).ToList());
            }
            public PartialViewResult BlogPartialLower()
            {

                return PartialView("~/Areas/Blog/Views/BlogPosts/_LowerBlogPartialView.cshtml", db.Posts.Where(s => s.Published).OrderByDescending(p => p.createdDate).Take(6).ToList());
            }
            public PartialViewResult BlogPartialLowLower()
            {

                return PartialView("~/Areas/Blog/Views/BlogPosts/_LowLowerBlogPartialView.cshtml", db.Topics.ToList());
            }

        public PartialViewResult BlogLogin()
        {
            return PartialView("~/Areas/Blog/Views/BlogPosts/_AccountLogin.cshtml");
        }

        public PartialViewResult BlogRegister()
        {
            return PartialView("~/Areas/Blog/Views/BlogPosts/_AccountRegister.cshtml");
        }

        public PartialViewResult BlogForgotPassword()
        {
            return PartialView("~/Areas/Blog/Views/BlogPosts/_AccountForgotPassword.cshtml");
        }

        public PartialViewResult BlogForgotPasswordConfirmation()
        {
            return PartialView("~/Areas/Blog/Views/BlogPosts/_AccountForgotPasswordConfirmation.cshtml");
        }
        public PartialViewResult BlogResetPassword()
        {
            return PartialView("~/Areas/Blog/Views/BlogPosts/_AccountResetPassword.cshtml");
        }

        public PartialViewResult BlogResetPasswordConfirmation()
        {
            return PartialView("~/Areas/Blog/Views/BlogPosts/_AccountResetPasswordConfirmation.cshtml");
        }

        public PartialViewResult RegistrationConfirmation()
        {
            return PartialView("~/Areas/Blog/Views/BlogPosts/_AccountRegistrationConfirmation.cshtml");
        }

        public PartialViewResult BlogAccess()
        {
            return PartialView("~/Areas/Blog/Views/BlogPosts/_AccountLoginAddRole.cshtml");
        }
    

        public ActionResult Search(int? page, string query)
            {
                int pageSize = 3;
                int pageNumber = (page ?? 1);
                ViewBag.Query = query;
                var queryposts = db.Posts.AsQueryable();
                var Published = db.Posts.Where(s => s.Published).ToList();
                if (!String.IsNullOrWhiteSpace(query)) //means if the query is coming in
                {
                    queryposts = queryposts.Where(p => p.Title.Contains(query) || p.Body.Contains(query) || p.Comments.Any(c => c.Body.Contains(query) || c.Commenter.DisplayName.Contains(query)));
                }

                return View("Index", queryposts.OrderByDescending(p => p.createdDate).ToPagedList(pageNumber, pageSize));
            }

            //GET
            public ActionResult PendingPosts(int? page)
            {
                int pageSize = 3;
                int pageNumber = (page ?? 1);
                var unpublished = db.Posts.Where(s => s.Published == false).ToList();
                return View(unpublished.OrderByDescending(p => p.createdDate).ToPagedList(pageNumber, pageSize));

            }


            public ActionResult PublishPending(int? PendingPostId)
            {
                if (PendingPostId == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                var PendingPost = db.Posts.FirstOrDefault(s => s.Id == PendingPostId);
                if (PendingPost == null)
                {
                    return HttpNotFound();
                }

                PendingPost.createdDate = DateTime.Now;
                PendingPost.Published = true;
                db.Entry(PendingPost).Property("Published").IsModified = true;
                db.SaveChanges();

                return RedirectToAction("Index");
            }



            public ActionResult Details(string Slug)
            {
                if (String.IsNullOrWhiteSpace(Slug))
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                BlogPost blogPost = db.Posts.FirstOrDefault(p => p.Slug == Slug
                );
                if (blogPost == null)
                {
                    return HttpNotFound();
                }
                return View(blogPost);
            }
            [Authorize(Roles = "Admin")]
            // GET: BlogPosts/Create
            public ActionResult Create()
            {
                ViewBag.Topics = new MultiSelectList(db.Topics, "Id", "TopicName");
                return View();
            }


            [HttpPost]
            [ValidateAntiForgeryToken]
            public ActionResult Create([Bind(Include = "Post, Topics")] BlogTopicsViewModel model, HttpPostedFileBase Image, string button)
            {
                if (ModelState.IsValid)
                {


                    var Slug = StringUtilities.URLFriendly(model.Post.Title);
                    if (String.IsNullOrWhiteSpace(Slug))
                    {
                        ModelState.AddModelError("Title", "Invalid title");
                        return View(model);
                    }
                    if (db.Posts.Any(p => p.Slug == Slug))
                    {
                        ModelState.AddModelError("Title", "The title must be unique");
                        return View(model);
                    }
                    var ErrorMessage = "";
                    if (ImageUploadValidator.IsWebFriendlyImage(Image))
                    {
                        var fileName = Path.GetFileName(Image.FileName);
                        var customName = string.Format(Guid.NewGuid() + fileName);
                        Image.SaveAs(Path.Combine(Server.MapPath("~/NEWIMAGES/"), customName));
                        model.Post.MediaURL = "~/NEWIMAGES/" + customName;
                    }
                    else
                    {
                        ViewBag.ErrorMessage = "Please select an image between 1KB-2MB and in an approved format (.jpg, .bmp, .png, .gif)";



                        model.Post.MediaURL = "images/module-1.jpg";
                    }
                    model.Post.createdDate = DateTime.Now;

                    model.Post.Slug = Slug;
                    if (button == "Create")
                    {
                        model.Post.Published = false;
                    }
                    else
                    {
                        model.Post.Published = true;

                    }

                    db.Posts.Add(model.Post);
                    db.SaveChanges();

                    if (model.Topics != null)
                    {
                        foreach (var vm in model.Topics)
                        {
                            int topicId = Convert.ToInt32(vm);
                            helper.AddTopicToBlog(topicId, model.Post.Id);

                        }
                    }

                    return RedirectToAction("Index", new { message = ErrorMessage });


                }
                ViewBag.Topics = new MultiSelectList(db.Topics, "Id", "Description");
                return View(model);
            }


            [Authorize(Roles = "Admin")]
            public ActionResult Edit(int? id)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                BlogPost blogPost = db.Posts.Find(id);
                if (blogPost == null)
                {
                    return HttpNotFound();
                }

                BlogTopicsViewModel vm = new BlogTopicsViewModel()
                {
                    Post = blogPost
                };

                ViewBag.Topics = new MultiSelectList(db.Topics, "Id", "TopicName");
                return View(vm);
            }

            // POST: BlogPosts/Edit/5
            // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
            // more details see http://go.microsoft.com/fwlink/?LinkId=317598.

            [HttpPost]
            [ValidateAntiForgeryToken]
            public ActionResult Edit([Bind(Include = "Post, Topics")] BlogTopicsViewModel BlogTopicVM, HttpPostedFileBase image, string button)
            {
                if (ModelState.IsValid)

ASG/Areas/Blog/Views/BlogPosts/Create.cshtml
@model ASG.Areas.Blog.Models.BlogTopicsViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>
@*<p>@ViewBag.ErrorMessage</p>*@
@using (Html.BeginForm("Create", "BlogPosts", FormMethod.Post, new { enctype = "Multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <h4>BlogPost</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Topics, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ListBox("Topics", null, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Topics, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Post.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Post.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Post.Title, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Post.Body, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Post.Body, new { htmlAttributes = new { @class = "form-control", id = "cr", rows = "10" } })
                @Html.ValidationMessageFor(model => model.Post.Body, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Upload Images</label>
            <div class="col-md-10">
                <input type="file" name="Image" class="form-control" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Post.Published, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Post.Published)
                    @Html.ValidationMessageFor(model => model.Post.Published, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" name="button" class="btn btn-default" /><input type="submit" value="Publish" name="button" class="btn btn-default" />
            </div>
        </div>
    </div>
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
}

@section Scripts {

    <script src="~/Scripts/tinymce/tinymce.min.js"></script>
    <script src="~/Scripts/tinymce/jquery.tinymce.min.js"></script>
    <script>
        $('#cr').tinymce({});
    </script>

    @Scripts.Render("~/bundles/jqueryval")
}

ASG/Areas/Blog/Views/BlogPosts/DeleteReply.cshtml
@model ASG.Areas.Blog.Models.Reply

@{
    ViewBag.Title = "DeleteReply";
}

<h2>DeleteReply</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Reply</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Replier.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Replier.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SpecificComment.CommenterId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SpecificComment.CommenterId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Body)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Body)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.createdDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.createdDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.updatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.updatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.updatedReason)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.updatedReason)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Count)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Count)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ASG/Areas/Blog/Views/BlogPosts/EditComment.cshtml
@model ASG.Areas.Blog.Models.Comment

@{
    ViewBag.Title = "EditComment";
}
<div class="container" style="color:white;padding-bottom:500px">
    <h2>EditComment</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Comment</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
            <div class="form-group">
                @Html.LabelFor(model => model.Commenter.DisplayName, "Commenter", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Commenter.DisplayName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Commenter.DisplayName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Body, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.updatedReason, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.updatedReason, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.updatedReason, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>

ASG/Areas/Blog/Views/BlogPosts/EditReply.cshtml
@model ASG.Areas.Blog.Models.Reply

@{
    ViewBag.Title = "EditReply";
}

<h2>EditReply</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <h4>Reply</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        <div class="form-group">
            @Html.LabelFor(model => model.SpecificCommentId, "SpecificCommentId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SpecificCommentId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SpecificCommentId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Body, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.updatedReason, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.updatedReason, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.updatedReason, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ASG/Areas/Blog/Views/BlogPosts/_AccountForgotPasswordConfirmation.cshtml
@{
    ViewBag.Title = "Reset password confirmation";
}


<div class="modal fade" id="blogForgotPasswordConfirmation" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="background-color:rgba(0, 0, 0, 0.7)">
    <div class="vertical-alignment-helper">
        <div class="modal-dialog vertical-align-center">
            <div class="modal-content">
                <div class="modal-header mdtitle">
                    <button type="button" class="close" data-dismiss="modal">
                        <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
                    </button>
                    <h4 class="modal-title inner-brand" id="myModalLabel">Password Reset</h4>
                </div>
                <div class="modal-body" style="width:90%; text-align:center; padding:30px 50px 20px 50px; margin:auto">
                    <div>
                        <p>
                            Please check your email to reset your password.
                        </p>
                    </div>
                </div>
                <div class="modal-footer" style="text-align:center; padding-top:20px">
                    <div class="form-group">
                        <button type="button" class="btn btn-lg btn-secondary btn-block  letter-spacing-3" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

ASG/Areas/Blog/Views/BlogPosts/_AccountLogin.cshtml
@using ASG.Models
@model LoginViewModel


<div class="modal fade" id="blogLogin" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="background-color:rgba(0, 0, 0, 0.7)">
    <div class="vertical-alignment-helper">
        <div class="modal-dialog vertical-align-center">
            <div class="modal-content">
                <div class="modal-header mdtitle">
                    <button type="button" class="close" data-dismiss="modal">
                        <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
                    </button>
                    <h4 class="modal-title inner-brand" id="myLoginModalLabel">Log In</h4>
                </div>
                <section id="loginForm">
                    @using (Html.BeginForm("Login", "Account", new { area = "", ReturnUrl = ViewBag.ReturnUrl, Application = ViewBag.Application }, FormMethod.Post, new { @class = "form-horizontal", role = "form", id = "blogLoginForm" }))
                    {
                        <div class="modal-body" style="width:90%; text-align:center; padding:100px 50px 20px 50px; margin:auto">
                            @Html.AntiForgeryToken()
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(m => m.Application, new { Value = "Blog" })
                            <div class="form-group">
                                <div>
                                    @Html.TextBoxFor(m => m.Email, new { @class = "form-control", @placeholder = "Email Address" })
                                    @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                <div>
                                    @Html.PasswordFor(m => m.Password, new { @class = "form-control", @placeholder = "Password" })
                                    @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
                                </div>
                                <div style="color:lime; text-align:left; margin:15px; font-size:14px; line-height:1" id="BlogLoginErrors"></div>
                            </div>

                            <div class="form-group" style="text-align: left; padding-left:23px">
                                <div>
                                    <div class="checkbox">
                                        @Html.CheckBoxFor(m => m.RememberMe)
                                        <span>@Html.LabelFor(m => m.RememberMe)</span>
                                    </div>
                                </div>
                            </div>
                            <div style="margin-top:50px">
                                <a onclick="openRegisterModal(true)">Register as a new User</a><br />
                                <a onclick="openForgotPasswordModal(true)">Forgot your password?</a>
                            </div>
                        </div>
                            <div class="modal-footer" style="text-align:center; padding-top:20px">
                                <div class="form-group">
                                    <input class="btn btn-lg btn-primary btn-block  letter-spacing-3" id="BlogLoginSubmit" value="Login" style="margin:25px; width:90%; margin:auto" />
                                </div>
                            </div>
                    }
                </section>
            </div>
        </div>
    </div>
</div>

ASG/Areas/Blog/Views/BlogPosts/_MidBlogPartialView.cshtml
@model IEnumerable<ASG.Areas.Blog.Models.BlogPost>

<aside class="widget widget_recent_entries_custom">
    <div class="widget-title">Popular Posts</div>
    <ul>
        @foreach (var post in Model)
        {
            <li class="clearfix">
                <div class="wi"><a href="@Url.Action("Details", "BlogPosts", new { slug = post.Slug })"><img src="@Url.Content(post.MediaURL)" alt=""></a></div>
                @*<a href="@Url.Action("Details", "BlogPosts", new { slug = post.Slug })">@Html.DisplayFor(modelItem => item.Title)</a>*@
                <div class="wb"><a href="@Url.Action("Details", "BlogPosts", new { slug = post.Slug })">@Html.DisplayFor(modelItem => post.Title)</a> <span class="post-date">@Html.DisplayFor(modelItem => post.createdDate)</span></div>
            </li>
        }
    </ul>
</aside>

ASG/Areas/Blog/Views/BlogPosts/_UpperBlogPartialView.cshtml
@model IEnumerable<ASG.Areas.Blog.Models.Topic>


<aside class="widget widget_search">
    @using Microsoft.AspNet.Identity
    @if (Request.IsAuthenticated)
    {
        using (Html.BeginForm("LogOff", "Account", new { area = "", Application = "Blog" }, FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
        {
            @Html.AntiForgeryToken()
            <ul class="nav navbar-nav navbar-right">
                @if (!User.IsInRole("BlogUser"))
                {
                    <li>
                        <a onclick="openBlogAccessModal()">Full Access</a>
                    </li>
                }
                <li>
                    @Html.ActionLink("Hello " + User.Identity.GetUserName().Substring(0, User.Identity.GetUserName().LastIndexOf("@")) + "!", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage" })
                </li>
                <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
            </ul>
        }
    }
    else
    {
        <ul class="nav navbar-nav navbar-right" style="padding-right:25px">
            <li><a onclick="openRegisterModal()">Register</a></li>
            <li><a onclick="openLoginModal()">Login</a></li>
        </ul>
    }
    <br /><br />
    <div style="margin-top: 130px">
        @using (Html.BeginForm("Search", "BlogPosts"))
        {
            <input class="form-control" type="search" placeholder="Search Blog" value="@ViewBag.Query" name="query">
            <button class="search-button" style="top:15px !important" type="submit"><span class="ti-search"></span></button>
        }
    </div>
</aside>
<!-- Categories widget-->
<aside class="widget widget_categories">
    <div class="widget-title"><a href="@Url.Action("Index", "Topics")">Categories</a></div>
    <ul>
        @foreach (var topics in Model)
        {
            if (topics.Posts.Any())
            {
                <li><a href="@Url.Action("Details", "Topics", new { id = topics.Id })">@Html.DisplayFor(modelItem => topics.TopicName) (@topics.Posts.Count())</a></li>
            }
        }
    </ul>
</aside>