ASG/Areas/FinancialPlanner/Models/TransactionType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ASG.Areas.FinancialPlanner.Models
{
    public class TransactionType  //Income, Transfer, Expense
    {

        public TransactionType()
        {
            Transactions = new HashSet<Transaction>();
        }
        public int Id { get; set; }
        public string Name { get; set; }


        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}

ASG/Areas/FinancialPlanner/Controllers/TransactionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ASG.Areas.FinancialPlanner.Models;
using Microsoft.AspNet.Identity;
using ASG.Models;
using Newtonsoft.Json;

namespace ASG.Areas.FinancialPlanner.Controllers
{
    public class TransactionsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Transactions
        public ActionResult Index()
        {
            var transactions = db.Transactions.Include(t => t.TransactionCategory).Include(t => t.TransactionType);
            return View(transactions.ToList());
        }

        // GET: Transactions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Transaction transaction = db.Transactions.Find(id);
            if (transaction == null)
            {
                return HttpNotFound();
            }
            return View(transaction);
        }


        //Get: ModalPartial

        public PartialViewResult TransactionModal(string id, int? budgetId)
        {
            var userId = User.Identity.GetUserId();
            var user = db.Users.Find(userId);
            var categories = db.TransactionCategories.Where(c => c.CreatedByUserId == userId).ToList();

            var categoryOptions = (from tc in db.TransactionCategories
                                   where tc.CreatedByUserId == userId
                                   select new
                                   {
                                       label = tc.Name,
                                       value = tc.Name
                                   }).ToArray();
       
            string json = JsonConvert.SerializeObject(categoryOptions, Formatting.Indented);    
            ViewBag.autocompleteOptions = json;
          
            var household = user.Household;
            var accounts = db.Accounts.Where(a => a.AccountHolderUserId == userId);
            var userscategories = db.TransactionCategories.Where(t => t.CreatedByUserId == userId).ToList();
            var userhouseholdId = user.HouseholdId;
            var usersinhousehold = db.Users.Where(u => u.HouseholdId == userhouseholdId);
            var UserHousehold = user.Household.Name;
            var General = db.TransactionCategories.Where(t => t.Name == "General");
            var UserCategories = db.TransactionCategories.Where(t => t.CreatedByUserId == userId);
            ViewBag.UserCategories = userscategories;

            ViewBag.currentBudgetId = budgetId;
            if (!household.Budgets.Any())
            {
                ViewBag.BudgetAlert = "Oops, you haven't established any Budgets yet.  Click here to set up your budget to utilize the planner.";
            }

            if (!accounts.Any())
            {
                UrlHelper uh = new UrlHelper(this.ControllerContext.RequestContext);
                string url = uh.Action("Create", "FinancialAccounts", null);
                ViewBag.url = url;
                ViewBag.AccountAlert = "First, lets set up an account to start tracking your transactions.";

            }            

            var budgetsNotExpired = household.Budgets.Where(b => b.Expired == false);
            if (budgetsNotExpired != null)
            {
                ViewBag.BudgetId = new SelectList(budgetsNotExpired, "Id", "Name", budgetId);
            }
           
            ViewBag.FinancialAccountId = new SelectList(accounts, "Id", "Name");
            ViewBag.TransactionTypeId = new SelectList(db.TransactionTypes, "Id", "Name");
            return PartialView();
        }


        //GET Reconcile Modal
        public PartialViewResult ReconcileTransaction(int? id)
        {

            if (id == null)
            {
                return PartialView();
            }
            Transaction transaction = db.Transactions.Find(id);
            if (transaction == null)
            {
                return PartialView(HttpNotFound());
            }

            return PartialView(transaction);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ReconcileTransactionConfirm([Bind(Include = "Id,Title,Amount,CreatedDate,UpdatedDate,SubmitterUserId,TransactionTypeId,TransactionCategoryId,FinancialAccountId,BudgetId")] Transaction transaction)
        {
            if (ModelState.IsValid)
            {
                var thistransaction = db.Transactions.FirstOrDefault(t => t.Id == transaction.Id);
                thistransaction.Reconciled = true;
                db.Entry(thistransaction).Property("Reconciled").IsModified = true;

                var budget = db.Transactions.Find(transaction.Id).Budget;
                var BudgetId = db.Transactions.Find(transaction.Id).BudgetId;
                var FinancialAccountId = db.Transactions.Find(transaction.Id).FinancialAccountId;
                var SubmitterUserId = db.Transactions.Find(transaction.Id).SubmitterUserId;
                var TransactionCategoryId = db.Transactions.Find(transaction.Id).TransactionCategoryId;
                var TransactionTypeId = db.Transactions.Find(transaction.Id).TransactionTypeId;
                var TransactionTitle = db.Transactions.Find(transaction.Id).Title;
                var oldtransaction = db.Transactions.AsNoTracking().FirstOrDefault(t => t.Id.Equals(transaction.Id));
                var newtransactionamount = transaction.Amount;

                decimal difference = 0;

                if (oldtransaction.Amount == newtransactionamount)
                {
                    transaction.ReconciledAmount = 0;
                    transaction.Reconciled = true;
                }

                else if (oldtransaction.Amount != newtransactionamount)
                {
                    difference = newtransactionamount - oldtransaction.Amount;


                    Transaction newtransaction = new Transaction();
                    newtransaction.Amount = difference;
                    newtransaction.BudgetId = BudgetId;
                    newtransaction.CreatedDate = DateTime.Now;
                    newtransaction.FinancialAccountId = FinancialAccountId;
                    newtransaction.Reconciled = true;
                    newtransaction.SubmitterUserId = SubmitterUserId;
                    newtransaction.TransactionCategoryId = TransactionCategoryId;
                    newtransaction.TransactionTypeId = TransactionTypeId;
                    newtransaction.Title = TransactionTitle + " " + "reconciled amount";
                    newtransaction.ReconciledAmount = difference;
                    db.Transactions.Add(newtransaction);
                    if (budget.BudgetRemaining > 0)
                    {
                        if ((budget.BudgetRemaining + difference) > 0)
                        {
                            budget.BudgetRemaining = budget.BudgetRemaining + difference;
                        }
                        else
                        {
                            budget.BudgetRemaining = 0;
                        }
                    }                 
                }

                db.SaveChanges();

                return RedirectToAction("Details", "Budgets", new { id = BudgetId });

            }
            return View(transaction);
        }



        // GET: Transactions/Create
        public ActionResult CreateBudgetTransaction(int? Id)
        {
            if (Id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Budget budget = db.Budgets.Find(Id);

            if (budget == null)
            {
                return HttpNotFound();
            }
            ViewBag.BudgetId = Id.GetValueOrDefault();
            ViewBag.WhichBudget = budget.Name;
            ViewBag.TransactionCategoryId = new SelectList(db.TransactionCategories, "Id", "Name");
            ViewBag.TransactionTypeId = new SelectList(db.TransactionTypes, "Id", "Name");
            return View();
        }

        // POST: Transactions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateBudgetTransaction([Bind(Include = "Id,Title,Amount,TransactionTypeId, BudgetId, FinancialAccountId")] Transaction transaction, string TransactionCategoryName)
        {
            if (ModelState.IsValid)
            {

                var userId = User.Identity.GetUserId();
                var user = db.Users.Find(userId);
                var useraccounts = db.Accounts.Where(a => a.AccountHolderUserId == userId).ToList();
                if (useraccounts != null)
                {
                    transaction.Reconciled = false;
                    transaction.SubmitterUserId = userId;
                    transaction.CreatedDate = DateTime.Now;
                    Budget budget = db.Budgets.Find(transaction.BudgetId);
                    FinancialAccount financialaccount = db.Accounts.Find(transaction.FinancialAccountId);

                    var TransactionCategory = db.TransactionCategories.FirstOrDefault(tc => tc.Name == TransactionCategoryName);
                    if (TransactionCategory != null)
                    {
                        transaction.TransactionCategoryId = TransactionCategory.Id;
                    }
                    else
                    {
                        TransactionCategory transactionCategory = new TransactionCategory();
                        transactionCategory.Name = TransactionCategoryName;

ASG/Areas/FinancialPlanner/Views/Transactions/Delete.cshtml
@model ASG.Areas.FinancialPlanner.Models.Transaction
@{ Layout = null;}
@{
    ViewBag.Title = "TransactionReconcileModal";
}


<div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"><img src="~/Areas/FinancialPlanner/FP_Images/fp.png" /></h4>
    </div>
    <div class="modal-body fpModal" style="padding-bottom:35px">
        <div class="container">
            <div class="row">
            </div>
        </div>
        Are you sure you want to delete this transaction?
        <hr />
        <dl class="dl-flex">
            <dt>
                @Html.DisplayNameFor(model => model.Title)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Title)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.TransactionCategory.Name)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.TransactionCategory.Name)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.TransactionType.Name)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.TransactionType.Name)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Amount)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Amount)
            </dd>
            <dt>
                Created Date
            </dt>
            <dd>
                @Html.DisplayFor(model => model.CreatedDate)
            </dd>
            <dt>
                Updated Date
            </dt>
            @if (Model.UpdatedDate != null)
            {
                <dd>
                    @Html.DisplayFor(model => model.UpdatedDate)
                </dd>
            }
            else
            {
                <dd>
                    N/A
                </dd>
            }
        </dl>
        @using (Html.BeginForm("DeleteConfirmed", "Transactions"))
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(m => m.Id)
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Delete" class="btn btn-default" style="float:right;" /><br /><br /><br />
                </div>
            </div>
        }
    </div>
</div>

ASG/Areas/FinancialPlanner/Views/Transactions/Index.cshtml
@model IEnumerable<ASG.Areas.FinancialPlanner.Models.Transaction>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TransactionCategory.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TransactionType.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Amount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SubmitterUserId)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TransactionCategory.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TransactionType.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Amount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UpdatedDate)td>
            <td>
                @Html.DisplayFor(modelItem => item.SubmitterUserId)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

ASG/Areas/FinancialPlanner/Views/Transactions/ReconcileTransaction.cshtml
@model ASG.Areas.FinancialPlanner.Models.Transaction
@{ Layout = null;}
@{
    ViewBag.Title = "TransactionReconcileModal";
}


<div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"><img src="~/Areas/FinancialPlanner/FP_Images/fp.png" /></h4>
    </div>
    <div class="modal-body fpModal">
        <div class="container">
            <div class="row">
            </div>
        </div>
        Reconcile your transaction<br /><br />
        @using (Html.BeginForm("ReconcileTransactionConfirm", "Transactions"))
            {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(m => m.Id)
            @Html.HiddenFor(m => m.BudgetId)
            @Html.HiddenFor(m => m.Reconciled)
            @Html.HiddenFor(m => m.FinancialAccountId)
            @Html.HiddenFor(m => m.SubmitterUserId)
            @Html.HiddenFor(m => m.TransactionCategoryId)
            @Html.HiddenFor(m => m.TransactionTypeId)
            @Html.HiddenFor(m => m.Title)

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-default" style="float:right" />
                    </div>
                </div>
            </div>
        }
    </div>
</div>

ASG/Areas/FinancialPlanner/Views/Transactions/TransactionModal.cshtml
@model ASG.Areas.FinancialPlanner.Models.Transaction
@{ Layout = null;}
@using Microsoft.AspNet.Identity


@{ var userid = User.Identity.GetUserId();

}
@{
    ViewBag.Title = "TransactionModal";
}

<link href="~/Areas/FinancialPlanner/FP_css/FP_css.css" rel="stylesheet" />
<style>
    ul.ui-autocomplete {
        z-index: 1100;
    }
</style>
<div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"><img src="~/Areas/FinancialPlanner/FP_Images/fp.png" /></h4>
    </div>
    <div class="modal-body fpModal">
        <div>
            <div class="row">
                @ViewBag.AccountAlert
                <br />
                @ViewBag.BudgetAlert

            </div>
        </div>
        <section id="">
            @if (ViewBag.AccountAlert == null && ViewBag.BudgetAlert == null)
            {
                using (Html.BeginForm("CreateBudgetTransaction", "Transactions", new { area = "FinancialPlanner", ReturnUrl = ViewBag.ReturnUrl, Application = ViewBag.Application }, FormMethod.Post, new { @class = "form-horizontal", role = "form", id = "TransactionForm" }))
                {
                    @Html.AntiForgeryToken()
                    <div class="form-horizontal" id="">
                        <div class="col-md-offset-1">
                            Enter a transaction below<br /><br />
                        </div>
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            <div class="col-md-10 col-md-offset-1">
                                Transaction Description
                                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-10 col-md-offset-1">
                                How much was this transaction for?
                                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-10 col-md-offset-1">
                                Was this a debit or a credit?
                                @Html.DropDownList("TransactionTypeId", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.TransactionTypeId, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-10 col-md-offset-1">
                                Find the type of transaction below or enter a new category
                                @Html.TextBox("TransactionCategoryName", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.TransactionCategory, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-10 col-md-offset-1">
                                Which of your budgets was the transaction for?
                                @Html.DropDownList("BudgetId", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.BudgetId, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-10 col-md-offset-1">
                                Which of your accounts did you use?
                                @Html.DropDownList("FinancialAccountId", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.FinancialAccountId, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="col-md-10 col-md-offset-1">
                            <span style="text-align:center; color:lime;" id="tempMessage">
                            </span>
                        </div>
                        <div class="form-group">
                            <div class="col-md-10 col-md-offset-1">
                                <input type="button" id="TransactionSubmit" value="Save" class="btn btn-default" style="float:right; width:120px" />
                            </div>
                        </div>
                    </div>
                }
            }
            else
            {
                <br /><br />
                <a type="button" class="btn  btn-default" style="margin-bottom:7px" href="@Url.Action("Create", "FinancialAccounts")" data-toggle="modal" data-target="#myModal2">Add an Account</a><br />
            }
        </section>
    </div>
</div>
<script>

    function ready(callback){
        // in case the document is already rendered
        if (document.readyState!='loading') callback();
            // modern browsers
        else if (document.addEventListener) document.addEventListener('DOMContentLoaded', callback);
            // IE <= 8
        else document.attachEvent('onreadystatechange', function(){
            if (document.readyState=='complete') callback();
        });
    }

    ready(function(){
        @if(Model != null)
        {
            @:debugger;
                    var x = @Html.Raw(Json.Encode(Model.BudgetId));
        }
        var budgetId = 0;

        @if (ViewBag.currentBudgetId != null)
        {
            @:budgetId = @ViewBag.currentBudgetId;
                }

        var availableTags = []
        $.ajax({
            type: "POST",
            data: { id: budgetId },
            url: "/FinancialPlanner/Budgets/CatDropdown",
            success: function (data) {
                if (data) {
                    availableTags = $.map(data, function (item) {
                        return {
                            label: item,
                            value: item
                        };
                    });
                    $('#TransactionCategoryName').autocomplete({
                        source: availableTags,
                        minLength: 0,
                        scroll: true
                    }).focus(function() {
                        $(this).autocomplete("search", "");
                    });

                }
            }
        })
    });
    $(function () {
        @if(Model != null)
        {
            @:debugger;
                                    var x = @Html.Raw(Json.Encode(Model.BudgetId));
        }
        var budgetId = 0;

        @if (ViewBag.currentBudgetId != null)
        {
            @:budgetId = @ViewBag.currentBudgetId;
                        }

        var availableTags = []
        $.ajax({
            type: "POST",
            data: { id: budgetId },
            url: "/FinancialPlanner/Budgets/CatDropdown",
            success: function (data) {
                if (data) {
                    availableTags = $.map(data, function (item) {
                        return {
                            label: item,
                            value: item
                        };
                    });
                    $('#TransactionCategoryName').autocomplete({
                        source: availableTags,
                        minLength: 0,
                        scroll: true
                    }).focus(function() {
                        $(this).autocomplete("search", "");
                    });

                }
            }
        })
    });


    $('#TransactionSubmit').click(function () {
        var form = $("#TransactionForm").serialize();
        $.ajax({
            type: "POST",
            url: "/FinancialPlanner/Transactions/CreateBudgetTransaction",
            data: $("#TransactionForm").serialize(),
            success: function (data) {
                if (!data.success) {
                    document.getElementById('tempMessage').innerHTML = data.ex.join('<br />');
                }
                else {
                    location.reload();
                }
            }
        });
    });
</script>

ASG/Areas/FinancialPlanner/Views/Transactions/Unvoid.cshtml
@model ASG.Areas.FinancialPlanner.Models.Transaction
@{ Layout = null;}
@{
    ViewBag.Title = "TransactionReconcileModal";
}

<div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"><img src="~/Areas/FinancialPlanner/FP_Images/fp.png" /></h4>
    </div>
    <div class="modal-body fpModal">
        <div class="container">
            <div class="row">
            </div>
        </div>      
        @using (Html.BeginForm("UnvoidConfirmed", "Transactions"))
            {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(m => m.Id)
            @Html.HiddenFor(m => m.BudgetId)
            @Html.HiddenFor(m => m.Reconciled)
            @Html.HiddenFor(m => m.FinancialAccountId)
            @Html.HiddenFor(m => m.SubmitterUserId)
            @Html.HiddenFor(m => m.TransactionCategoryId)
            @Html.HiddenFor(m => m.TransactionTypeId)
            @Html.HiddenFor(m => m.Title)
            <div class="form-horizontal">
                <h4>Unvoid</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-default" style="float:right" />
                    </div>
                </div>
            </div>
        }     
    </div>   
</div>

ASG/Areas/FinancialPlanner/Views/Transactions/Void.cshtml
@model ASG.Areas.FinancialPlanner.Models.Transaction
@{ Layout = null;}
@{
    ViewBag.Title = "TransactionReconcileModal";
}

<div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"><img src="~/Areas/FinancialPlanner/FP_Images/fp.png" /></h4>
    </div>
    <div class="modal-body fpModal">
        <div class="container">
            <div class="row">
            </div>
        </div>
        Are you sure you want to void this transaction?
        <div>
            <hr />
            <dl class="dl-flex">
                <dt>
                    Transaction Category
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.TransactionCategory.Name)
                </dd>
                <dt>
                    Type of transaction
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.TransactionType.Name)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Title)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Title)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Amount)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Amount)
                </dd>
                <dt>
                    Created Date
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.CreatedDate)
                </dd>
                <dt>
                    Updated Date
                </dt>
                @if (Model.UpdatedDate != null)
                {
                    <dd>
                        @Html.DisplayFor(model => model.UpdatedDate)
                    </dd>
                }
                else
                {
                    <dd>
                        N/A
                    </dd>
                }
                <dt>
                    Submitted By
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.SubmitterUser.DisplayName)
                </dd>
            </dl>
            @using (Html.BeginForm("VoidConfirmed", "Transactions"))
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(m => m.Id)
                <div class="form-actions no-color">
                    <input type="submit" value="Void" class="btn btn-default" style="width:150px; float:right" />
                    @Html.HiddenFor(m => m.BudgetId)
                </div><br /><br />
            }
        </div>
    </div>
</div>